service: backend
frameworkVersion: '2 || 3'
	
plugins:
  # use serverless-python-requirements plugin to install pip dependencies
  - serverless-python-requirements

custom:
  # name for the S3 bucket that will contain boards
  boardsBucketName: urtask-boards-${sls:stage}
  # use docker container to build/package dependencies
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: us-east-1
  environment:
    BOARDS_BUCKET_NAME: ${self:custom.boardsBucketName}

functions:
  create_board:
    handler: handler.create_board
    events:
      - httpApi:
          path: /boards
          method: post
  update_board:
    handler: handler.update_board
    events:
      - httpApi:
          path: /boards/{board_id}
          method: put
  delete_board:
    handler: handler.delete_board
    events:
      - httpApi:
          path: /boards/{board_id}
          method: delete
  get_board:
    handler: handler.get_board
    events:
      - httpApi:
          path: /boards/{board_id}
          method: get

resources:
  Resources:
    # S3 bucket that contains individual boards
    boardsBucket:
      Type: AWS::S3::Bucket
      Properties:
        # name of the bucket we configured earlier
        BucketName: ${self:custom.boardsBucketName}
        # configure to accept requests from all origins
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
